(ns fab_lithography.actor
  "fab_lithography clean-room actor — Clojure over the kotoba Datom log (EAVT, Datomic-isomorphic,
  ADR-2605262130 + ADR-2605312345). Semiconductor fab / EUV lithography process.

  Generated by 70-tools/scaffold_wave11_clj_datomic.py — replaces the Python main.py.
  CRUD + validation over a DI `DatomPort` seam (no external managed DB; the production
  adapter is kotoba-kqe, the test/browser adapter is `in-memory-datom`). No proprietary code."
  (:require [clojure.string :as str]))

;; ── Datomic-style schema (install via -transact) ──────────────────────────
(def schema
  "Attribute installs for this actor's entities (Datomic schema shape)."
  [;; Wafer
   {:db/ident :fab_lithography.Wafer/id :db/valueType :db.type/string :db/cardinality :db.cardinality/one :db/unique :db.unique/identity}
   {:db/ident :fab_lithography.Wafer/lotId :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :fab_lithography.Wafer/diameterMm :db/valueType :db.type/long :db/cardinality :db.cardinality/one}
   {:db/ident :fab_lithography.Wafer/processNode :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :fab_lithography.Wafer/status :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :fab_lithography.Wafer/createdAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   {:db/ident :fab_lithography.Wafer/updatedAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   ;; ProcessStep
   {:db/ident :fab_lithography.ProcessStep/id :db/valueType :db.type/string :db/cardinality :db.cardinality/one :db/unique :db.unique/identity}
   {:db/ident :fab_lithography.ProcessStep/waferId :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :fab_lithography.ProcessStep/name :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :fab_lithography.ProcessStep/tool :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :fab_lithography.ProcessStep/stepType :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :fab_lithography.ProcessStep/createdAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   {:db/ident :fab_lithography.ProcessStep/updatedAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   ;; Reticle
   {:db/ident :fab_lithography.Reticle/id :db/valueType :db.type/string :db/cardinality :db.cardinality/one :db/unique :db.unique/identity}
   {:db/ident :fab_lithography.Reticle/name :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :fab_lithography.Reticle/layer :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :fab_lithography.Reticle/euv :db/valueType :db.type/boolean :db/cardinality :db.cardinality/one}
   {:db/ident :fab_lithography.Reticle/numericalAperture :db/valueType :db.type/double :db/cardinality :db.cardinality/one}
   {:db/ident :fab_lithography.Reticle/createdAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   {:db/ident :fab_lithography.Reticle/updatedAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   ;; ProcessRecipe
   {:db/ident :fab_lithography.ProcessRecipe/id :db/valueType :db.type/string :db/cardinality :db.cardinality/one :db/unique :db.unique/identity}
   {:db/ident :fab_lithography.ProcessRecipe/stepId :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :fab_lithography.ProcessRecipe/name :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :fab_lithography.ProcessRecipe/doseMjCm2 :db/valueType :db.type/double :db/cardinality :db.cardinality/one}
   {:db/ident :fab_lithography.ProcessRecipe/focusNm :db/valueType :db.type/double :db/cardinality :db.cardinality/one}
   {:db/ident :fab_lithography.ProcessRecipe/createdAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   {:db/ident :fab_lithography.ProcessRecipe/updatedAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   ;; DefectScan
   {:db/ident :fab_lithography.DefectScan/id :db/valueType :db.type/string :db/cardinality :db.cardinality/one :db/unique :db.unique/identity}
   {:db/ident :fab_lithography.DefectScan/waferId :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :fab_lithography.DefectScan/defectCount :db/valueType :db.type/long :db/cardinality :db.cardinality/one}
   {:db/ident :fab_lithography.DefectScan/defectDensity :db/valueType :db.type/double :db/cardinality :db.cardinality/one}
   {:db/ident :fab_lithography.DefectScan/classification :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :fab_lithography.DefectScan/createdAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   {:db/ident :fab_lithography.DefectScan/updatedAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   ;; Yield
   {:db/ident :fab_lithography.Yield/id :db/valueType :db.type/string :db/cardinality :db.cardinality/one :db/unique :db.unique/identity}
   {:db/ident :fab_lithography.Yield/waferId :db/valueType :db.type/string :db/cardinality :db.cardinality/one}
   {:db/ident :fab_lithography.Yield/dieTotal :db/valueType :db.type/long :db/cardinality :db.cardinality/one}
   {:db/ident :fab_lithography.Yield/dieGood :db/valueType :db.type/long :db/cardinality :db.cardinality/one}
   {:db/ident :fab_lithography.Yield/yieldPct :db/valueType :db.type/double :db/cardinality :db.cardinality/one}
   {:db/ident :fab_lithography.Yield/createdAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}
   {:db/ident :fab_lithography.Yield/updatedAt :db/valueType :db.type/instant :db/cardinality :db.cardinality/one}])

(def entities #{"Wafer" "ProcessStep" "Reticle" "ProcessRecipe" "DefectScan" "Yield"})

;; ── DatomPort — the DI seam to the kotoba Datom log ───────────────────────
(defprotocol DatomPort
  (-transact [this tx-data]
    "Append Datomic-shaped tx-data: entity maps {:db/id … attr v}, [:db/add e a v],
     [:db/retract e a v], [:db/retractEntity e].")
  (-pull [this eid]
    "Return the entity map for eid (incl. :db/id), or nil.")
  (-find-by-attr [this attr]
    "AEVT scan: the eids of every entity carrying attr."))

;; loud-failing default — a forgotten injection must never silently no-op
(defn unwired-datom []
  (reify DatomPort
    (-transact [_ _] (throw (ex-info "fab_lithography: DatomPort not wired — inject kotoba-kqe or in-memory-datom" {:unwired true})))
    (-pull [_ _] (throw (ex-info "fab_lithography: DatomPort not wired" {:unwired true})))
    (-find-by-attr [_ _] (throw (ex-info "fab_lithography: DatomPort not wired" {:unwired true})))))

;; in-memory fake — interprets the Datomic tx-data subset over {eid {attr v}}
(defn in-memory-datom []
  (let [store (atom {})]
    (reify DatomPort
      (-transact [_ tx-data]
        (doseq [op tx-data]
          (cond
            (map? op) (swap! store update (:db/id op) merge (dissoc op :db/id))
            (and (vector? op) (= :db/add (first op)))
            (let [[_ e a v] op] (swap! store assoc-in [e a] v))
            (and (vector? op) (= :db/retract (first op)))
            (let [[_ e a] op] (swap! store update e dissoc a))
            (and (vector? op) (= :db/retractEntity (first op)))
            (let [[_ e] op] (swap! store dissoc e))))
        {:db-after @store})
      (-pull [_ eid] (when-let [m (get @store eid)] (assoc m :db/id eid)))
      (-find-by-attr [_ attr] (vec (for [[eid m] @store :when (contains? m attr)] eid))))))

;; ── coercion (portable) ───────────────────────────────────────────────────
(defn- as-long [v]
  (cond (number? v) #?(:clj (long v) :cljs v)
        (string? v) (try #?(:clj (Long/parseLong (str/trim v))
                            :cljs (let [n (js/parseInt v 10)] (if (js/isNaN n) 0 n)))
                         (catch #?(:clj Exception :cljs :default) _ 0))
        :else 0))

(defn- as-double [v]
  (cond (number? v) #?(:clj (double v) :cljs v)
        (string? v) (try #?(:clj (Double/parseDouble (str/trim v))
                            :cljs (let [n (js/parseFloat v)] (if (js/isNaN n) 0.0 n)))
                         (catch #?(:clj Exception :cljs :default) _ 0.0))
        :else 0.0))

(defn- as-bool [v]
  (boolean (#{"1" "true" "yes" "on" true} (if (string? v) (str/lower-case v) v))))

(defn- now []
  #?(:clj (str (java.time.Instant/now)) :cljs (.toISOString (js/Date.))))

(defn- new-id [prefix]
  (str prefix "_" (subs (str/replace (str (random-uuid)) "-" "") 0 16)))

(defn- require-fields [data fields]
  (let [missing (remove (fn [k] (some? (get data (keyword k)))) fields)]
    (when (seq missing)
      (throw (ex-info (str "Missing required fields: " (str/join ", " missing))
                      {:type :invalid-request :missing (vec missing)})))))

;; ── list surface: filtering + cursor pagination (L4 parity) ───────────────
(def ^:const default-limit 20)
(def ^:const max-limit 100)

(defn- index-of [v x]
  (loop [i 0] (cond (>= i (count v)) -1 (= (nth v i) x) i :else (recur (inc i)))))

(defn- apply-filters
  "Keep rows matching every {attr v} in flt (string-compared), attr restricted to allowed."
  [rows flt allowed]
  (let [allowed (set allowed)]
    (reduce (fn [rs [a v]]
              (if (and (contains? allowed a) (some? v))
                (filterv (fn [r] (= (str (get r a)) (str v))) rs)
                rs))
            (vec rows) (or flt {}))))

(defn- paginate
  "Cursor pagination over rows → {:object :data :has-more :count :total}.
   opts {:limit N :starting-after <db/id>}."
  [rows opts]
  (let [limit (min (max (or (:limit opts) default-limit) 1) max-limit)
        start (:starting-after opts)
        rows  (vec rows)
        rows  (if start
                (let [idx (index-of (mapv :db/id rows) start)]
                  (if (neg? idx) rows (subvec rows (inc idx))))
                rows)
        page  (vec (take limit rows))]
    {:object "list" :data page :has-more (> (count rows) limit)
     :count (count page) :total (count rows)}))

;; ── Wafer ────────────────────────────────────────────────────────────────
(defn create-wafer
  "Create a Wafer."
  [port data]
  (require-fields data ["diameterMm" "processNode"])
  (let [id (new-id "fab_waf")
        e {:db/id id
           :fab_lithography.Wafer/id id
           :fab_lithography.Wafer/lotId (get data :lotId)
           :fab_lithography.Wafer/diameterMm (as-long (get data :diameterMm))
           :fab_lithography.Wafer/processNode (get data :processNode)
           :fab_lithography.Wafer/status (get data :status)
           :fab_lithography.Wafer/createdAt (now)
           :fab_lithography.Wafer/updatedAt (now)}]
    (-transact port [e])
    e))

(defn list-wafers
  "List Wafer with optional filtering + cursor pagination → L4 list map.
   opts: {:filter {<attr-kw> v} :limit N :starting-after <db/id>}."
  ([port] (list-wafers port {}))
  ([port opts]
   (let [rows (mapv (fn [e] (-pull port e)) (-find-by-attr port :fab_lithography.Wafer/id))
         rows (apply-filters rows (:filter opts) [:fab_lithography.Wafer/lotId :fab_lithography.Wafer/diameterMm :fab_lithography.Wafer/processNode :fab_lithography.Wafer/status])]
     (paginate rows opts))))

(defn get-wafer
  "Retrieve a Wafer by id; opts {:expand #{:field}} inlines referenced entities. nil if absent."
  ([port id] (get-wafer port id nil))
  ([port id opts]
   (when-let [rec (-pull port id)]
     (let [want (:expand opts)]
       (cond-> rec)))))

(defn update-wafer
  "Update a Wafer; returns the new entity map, or nil if absent."
  [port id data]
  (when (-pull port id)
    (let [sets (-> []
                   (cond-> (contains? data :lotId) (conj [:db/add id :fab_lithography.Wafer/lotId (get data :lotId)]))
                   (cond-> (contains? data :diameterMm) (conj [:db/add id :fab_lithography.Wafer/diameterMm (as-long (get data :diameterMm))]))
                   (cond-> (contains? data :processNode) (conj [:db/add id :fab_lithography.Wafer/processNode (get data :processNode)]))
                   (cond-> (contains? data :status) (conj [:db/add id :fab_lithography.Wafer/status (get data :status)]))
                   (conj [:db/add id :fab_lithography.Wafer/updatedAt (now)]))]
      (-transact port sets)
      (-pull port id))))

(defn delete-wafer
  "Delete a Wafer."
  [port id]
  (-transact port [[:db/retractEntity id]])
  {:id id :deleted true})

;; ── ProcessStep ────────────────────────────────────────────────────────────────
(defn create-process-step
  "Create a ProcessStep."
  [port data]
  (require-fields data ["name" "tool"])
  (let [id (new-id "fab_pro")
        e {:db/id id
           :fab_lithography.ProcessStep/id id
           :fab_lithography.ProcessStep/waferId (get data :waferId)
           :fab_lithography.ProcessStep/name (get data :name)
           :fab_lithography.ProcessStep/tool (get data :tool)
           :fab_lithography.ProcessStep/stepType (get data :stepType)
           :fab_lithography.ProcessStep/createdAt (now)
           :fab_lithography.ProcessStep/updatedAt (now)}]
    (-transact port [e])
    e))

(defn list-process-steps
  "List ProcessStep with optional filtering + cursor pagination → L4 list map.
   opts: {:filter {<attr-kw> v} :limit N :starting-after <db/id>}."
  ([port] (list-process-steps port {}))
  ([port opts]
   (let [rows (mapv (fn [e] (-pull port e)) (-find-by-attr port :fab_lithography.ProcessStep/id))
         rows (apply-filters rows (:filter opts) [:fab_lithography.ProcessStep/waferId :fab_lithography.ProcessStep/name :fab_lithography.ProcessStep/tool :fab_lithography.ProcessStep/stepType])]
     (paginate rows opts))))

(defn get-process-step
  "Retrieve a ProcessStep by id; opts {:expand #{:field}} inlines referenced entities. nil if absent."
  ([port id] (get-process-step port id nil))
  ([port id opts]
   (when-let [rec (-pull port id)]
     (let [want (:expand opts)]
       (cond-> rec
         (and want (contains? want :waferId) (get rec :fab_lithography.ProcessStep/waferId))
         (assoc :waferId-obj (-pull port (get rec :fab_lithography.ProcessStep/waferId))))))))

(defn update-process-step
  "Update a ProcessStep; returns the new entity map, or nil if absent."
  [port id data]
  (when (-pull port id)
    (let [sets (-> []
                   (cond-> (contains? data :waferId) (conj [:db/add id :fab_lithography.ProcessStep/waferId (get data :waferId)]))
                   (cond-> (contains? data :name) (conj [:db/add id :fab_lithography.ProcessStep/name (get data :name)]))
                   (cond-> (contains? data :tool) (conj [:db/add id :fab_lithography.ProcessStep/tool (get data :tool)]))
                   (cond-> (contains? data :stepType) (conj [:db/add id :fab_lithography.ProcessStep/stepType (get data :stepType)]))
                   (conj [:db/add id :fab_lithography.ProcessStep/updatedAt (now)]))]
      (-transact port sets)
      (-pull port id))))

(defn delete-process-step
  "Delete a ProcessStep."
  [port id]
  (-transact port [[:db/retractEntity id]])
  {:id id :deleted true})

;; ── Reticle ────────────────────────────────────────────────────────────────
(defn create-reticle
  "Create a Reticle."
  [port data]
  (require-fields data ["name" "layer"])
  (let [id (new-id "fab_ret")
        e {:db/id id
           :fab_lithography.Reticle/id id
           :fab_lithography.Reticle/name (get data :name)
           :fab_lithography.Reticle/layer (get data :layer)
           :fab_lithography.Reticle/euv (as-bool (get data :euv))
           :fab_lithography.Reticle/numericalAperture (as-double (get data :numericalAperture))
           :fab_lithography.Reticle/createdAt (now)
           :fab_lithography.Reticle/updatedAt (now)}]
    (-transact port [e])
    e))

(defn list-reticles
  "List Reticle with optional filtering + cursor pagination → L4 list map.
   opts: {:filter {<attr-kw> v} :limit N :starting-after <db/id>}."
  ([port] (list-reticles port {}))
  ([port opts]
   (let [rows (mapv (fn [e] (-pull port e)) (-find-by-attr port :fab_lithography.Reticle/id))
         rows (apply-filters rows (:filter opts) [:fab_lithography.Reticle/name :fab_lithography.Reticle/layer :fab_lithography.Reticle/euv :fab_lithography.Reticle/numericalAperture])]
     (paginate rows opts))))

(defn get-reticle
  "Retrieve a Reticle by id; opts {:expand #{:field}} inlines referenced entities. nil if absent."
  ([port id] (get-reticle port id nil))
  ([port id opts]
   (when-let [rec (-pull port id)]
     (let [want (:expand opts)]
       (cond-> rec)))))

(defn update-reticle
  "Update a Reticle; returns the new entity map, or nil if absent."
  [port id data]
  (when (-pull port id)
    (let [sets (-> []
                   (cond-> (contains? data :name) (conj [:db/add id :fab_lithography.Reticle/name (get data :name)]))
                   (cond-> (contains? data :layer) (conj [:db/add id :fab_lithography.Reticle/layer (get data :layer)]))
                   (cond-> (contains? data :euv) (conj [:db/add id :fab_lithography.Reticle/euv (as-bool (get data :euv))]))
                   (cond-> (contains? data :numericalAperture) (conj [:db/add id :fab_lithography.Reticle/numericalAperture (as-double (get data :numericalAperture))]))
                   (conj [:db/add id :fab_lithography.Reticle/updatedAt (now)]))]
      (-transact port sets)
      (-pull port id))))

(defn delete-reticle
  "Delete a Reticle."
  [port id]
  (-transact port [[:db/retractEntity id]])
  {:id id :deleted true})

;; ── ProcessRecipe ────────────────────────────────────────────────────────────────
(defn create-process-recipe
  "Create a ProcessRecipe."
  [port data]
  (require-fields data ["name" "doseMjCm2"])
  (let [id (new-id "fab_pro")
        e {:db/id id
           :fab_lithography.ProcessRecipe/id id
           :fab_lithography.ProcessRecipe/stepId (get data :stepId)
           :fab_lithography.ProcessRecipe/name (get data :name)
           :fab_lithography.ProcessRecipe/doseMjCm2 (as-double (get data :doseMjCm2))
           :fab_lithography.ProcessRecipe/focusNm (as-double (get data :focusNm))
           :fab_lithography.ProcessRecipe/createdAt (now)
           :fab_lithography.ProcessRecipe/updatedAt (now)}]
    (-transact port [e])
    e))

(defn list-process-recipes
  "List ProcessRecipe with optional filtering + cursor pagination → L4 list map.
   opts: {:filter {<attr-kw> v} :limit N :starting-after <db/id>}."
  ([port] (list-process-recipes port {}))
  ([port opts]
   (let [rows (mapv (fn [e] (-pull port e)) (-find-by-attr port :fab_lithography.ProcessRecipe/id))
         rows (apply-filters rows (:filter opts) [:fab_lithography.ProcessRecipe/stepId :fab_lithography.ProcessRecipe/name :fab_lithography.ProcessRecipe/doseMjCm2 :fab_lithography.ProcessRecipe/focusNm])]
     (paginate rows opts))))

(defn get-process-recipe
  "Retrieve a ProcessRecipe by id; opts {:expand #{:field}} inlines referenced entities. nil if absent."
  ([port id] (get-process-recipe port id nil))
  ([port id opts]
   (when-let [rec (-pull port id)]
     (let [want (:expand opts)]
       (cond-> rec)))))

(defn update-process-recipe
  "Update a ProcessRecipe; returns the new entity map, or nil if absent."
  [port id data]
  (when (-pull port id)
    (let [sets (-> []
                   (cond-> (contains? data :stepId) (conj [:db/add id :fab_lithography.ProcessRecipe/stepId (get data :stepId)]))
                   (cond-> (contains? data :name) (conj [:db/add id :fab_lithography.ProcessRecipe/name (get data :name)]))
                   (cond-> (contains? data :doseMjCm2) (conj [:db/add id :fab_lithography.ProcessRecipe/doseMjCm2 (as-double (get data :doseMjCm2))]))
                   (cond-> (contains? data :focusNm) (conj [:db/add id :fab_lithography.ProcessRecipe/focusNm (as-double (get data :focusNm))]))
                   (conj [:db/add id :fab_lithography.ProcessRecipe/updatedAt (now)]))]
      (-transact port sets)
      (-pull port id))))

(defn delete-process-recipe
  "Delete a ProcessRecipe."
  [port id]
  (-transact port [[:db/retractEntity id]])
  {:id id :deleted true})

;; ── DefectScan ────────────────────────────────────────────────────────────────
(defn create-defect-scan
  "Create a DefectScan."
  [port data]
  (require-fields data ["defectCount" "defectDensity"])
  (let [id (new-id "fab_def")
        e {:db/id id
           :fab_lithography.DefectScan/id id
           :fab_lithography.DefectScan/waferId (get data :waferId)
           :fab_lithography.DefectScan/defectCount (as-long (get data :defectCount))
           :fab_lithography.DefectScan/defectDensity (as-double (get data :defectDensity))
           :fab_lithography.DefectScan/classification (get data :classification)
           :fab_lithography.DefectScan/createdAt (now)
           :fab_lithography.DefectScan/updatedAt (now)}]
    (-transact port [e])
    e))

(defn list-defect-scans
  "List DefectScan with optional filtering + cursor pagination → L4 list map.
   opts: {:filter {<attr-kw> v} :limit N :starting-after <db/id>}."
  ([port] (list-defect-scans port {}))
  ([port opts]
   (let [rows (mapv (fn [e] (-pull port e)) (-find-by-attr port :fab_lithography.DefectScan/id))
         rows (apply-filters rows (:filter opts) [:fab_lithography.DefectScan/waferId :fab_lithography.DefectScan/defectCount :fab_lithography.DefectScan/defectDensity :fab_lithography.DefectScan/classification])]
     (paginate rows opts))))

(defn get-defect-scan
  "Retrieve a DefectScan by id; opts {:expand #{:field}} inlines referenced entities. nil if absent."
  ([port id] (get-defect-scan port id nil))
  ([port id opts]
   (when-let [rec (-pull port id)]
     (let [want (:expand opts)]
       (cond-> rec
         (and want (contains? want :waferId) (get rec :fab_lithography.DefectScan/waferId))
         (assoc :waferId-obj (-pull port (get rec :fab_lithography.DefectScan/waferId))))))))

(defn update-defect-scan
  "Update a DefectScan; returns the new entity map, or nil if absent."
  [port id data]
  (when (-pull port id)
    (let [sets (-> []
                   (cond-> (contains? data :waferId) (conj [:db/add id :fab_lithography.DefectScan/waferId (get data :waferId)]))
                   (cond-> (contains? data :defectCount) (conj [:db/add id :fab_lithography.DefectScan/defectCount (as-long (get data :defectCount))]))
                   (cond-> (contains? data :defectDensity) (conj [:db/add id :fab_lithography.DefectScan/defectDensity (as-double (get data :defectDensity))]))
                   (cond-> (contains? data :classification) (conj [:db/add id :fab_lithography.DefectScan/classification (get data :classification)]))
                   (conj [:db/add id :fab_lithography.DefectScan/updatedAt (now)]))]
      (-transact port sets)
      (-pull port id))))

(defn delete-defect-scan
  "Delete a DefectScan."
  [port id]
  (-transact port [[:db/retractEntity id]])
  {:id id :deleted true})

;; ── Yield ────────────────────────────────────────────────────────────────
(defn create-yield
  "Create a Yield."
  [port data]
  (require-fields data ["dieTotal" "dieGood"])
  (let [id (new-id "fab_yie")
        e {:db/id id
           :fab_lithography.Yield/id id
           :fab_lithography.Yield/waferId (get data :waferId)
           :fab_lithography.Yield/dieTotal (as-long (get data :dieTotal))
           :fab_lithography.Yield/dieGood (as-long (get data :dieGood))
           :fab_lithography.Yield/yieldPct (as-double (get data :yieldPct))
           :fab_lithography.Yield/createdAt (now)
           :fab_lithography.Yield/updatedAt (now)}]
    (-transact port [e])
    e))

(defn list-yields
  "List Yield with optional filtering + cursor pagination → L4 list map.
   opts: {:filter {<attr-kw> v} :limit N :starting-after <db/id>}."
  ([port] (list-yields port {}))
  ([port opts]
   (let [rows (mapv (fn [e] (-pull port e)) (-find-by-attr port :fab_lithography.Yield/id))
         rows (apply-filters rows (:filter opts) [:fab_lithography.Yield/waferId :fab_lithography.Yield/dieTotal :fab_lithography.Yield/dieGood :fab_lithography.Yield/yieldPct])]
     (paginate rows opts))))

(defn get-yield
  "Retrieve a Yield by id; opts {:expand #{:field}} inlines referenced entities. nil if absent."
  ([port id] (get-yield port id nil))
  ([port id opts]
   (when-let [rec (-pull port id)]
     (let [want (:expand opts)]
       (cond-> rec
         (and want (contains? want :waferId) (get rec :fab_lithography.Yield/waferId))
         (assoc :waferId-obj (-pull port (get rec :fab_lithography.Yield/waferId))))))))

(defn update-yield
  "Update a Yield; returns the new entity map, or nil if absent."
  [port id data]
  (when (-pull port id)
    (let [sets (-> []
                   (cond-> (contains? data :waferId) (conj [:db/add id :fab_lithography.Yield/waferId (get data :waferId)]))
                   (cond-> (contains? data :dieTotal) (conj [:db/add id :fab_lithography.Yield/dieTotal (as-long (get data :dieTotal))]))
                   (cond-> (contains? data :dieGood) (conj [:db/add id :fab_lithography.Yield/dieGood (as-long (get data :dieGood))]))
                   (cond-> (contains? data :yieldPct) (conj [:db/add id :fab_lithography.Yield/yieldPct (as-double (get data :yieldPct))]))
                   (conj [:db/add id :fab_lithography.Yield/updatedAt (now)]))]
      (-transact port sets)
      (-pull port id))))

(defn delete-yield
  "Delete a Yield."
  [port id]
  (-transact port [[:db/retractEntity id]])
  {:id id :deleted true})

;; ── REST surface (host wires these to the kotoba-clj gateway) ──────────────
(def routes
  [{:method "POST" :path "/v1/wafers" :op :create :entity "Wafer"}
   {:method "GET" :path "/v1/wafers" :op :list :entity "Wafer"}
   {:method "GET" :path "/v1/wafers/:id" :op :get :entity "Wafer"}
   {:method "PATCH" :path "/v1/wafers/:id" :op :update :entity "Wafer"}
   {:method "DELETE" :path "/v1/wafers/:id" :op :delete :entity "Wafer"}
   {:method "POST" :path "/v1/processsteps" :op :create :entity "ProcessStep"}
   {:method "GET" :path "/v1/processsteps" :op :list :entity "ProcessStep"}
   {:method "GET" :path "/v1/processsteps/:id" :op :get :entity "ProcessStep"}
   {:method "PATCH" :path "/v1/processsteps/:id" :op :update :entity "ProcessStep"}
   {:method "DELETE" :path "/v1/processsteps/:id" :op :delete :entity "ProcessStep"}
   {:method "POST" :path "/v1/reticles" :op :create :entity "Reticle"}
   {:method "GET" :path "/v1/reticles" :op :list :entity "Reticle"}
   {:method "GET" :path "/v1/reticles/:id" :op :get :entity "Reticle"}
   {:method "PATCH" :path "/v1/reticles/:id" :op :update :entity "Reticle"}
   {:method "DELETE" :path "/v1/reticles/:id" :op :delete :entity "Reticle"}
   {:method "POST" :path "/v1/processrecipes" :op :create :entity "ProcessRecipe"}
   {:method "GET" :path "/v1/processrecipes" :op :list :entity "ProcessRecipe"}
   {:method "GET" :path "/v1/processrecipes/:id" :op :get :entity "ProcessRecipe"}
   {:method "PATCH" :path "/v1/processrecipes/:id" :op :update :entity "ProcessRecipe"}
   {:method "DELETE" :path "/v1/processrecipes/:id" :op :delete :entity "ProcessRecipe"}
   {:method "POST" :path "/v1/defectscans" :op :create :entity "DefectScan"}
   {:method "GET" :path "/v1/defectscans" :op :list :entity "DefectScan"}
   {:method "GET" :path "/v1/defectscans/:id" :op :get :entity "DefectScan"}
   {:method "PATCH" :path "/v1/defectscans/:id" :op :update :entity "DefectScan"}
   {:method "DELETE" :path "/v1/defectscans/:id" :op :delete :entity "DefectScan"}
   {:method "POST" :path "/v1/yields" :op :create :entity "Yield"}
   {:method "GET" :path "/v1/yields" :op :list :entity "Yield"}
   {:method "GET" :path "/v1/yields/:id" :op :get :entity "Yield"}
   {:method "PATCH" :path "/v1/yields/:id" :op :update :entity "Yield"}
   {:method "DELETE" :path "/v1/yields/:id" :op :delete :entity "Yield"}])

;; collection → CRUD fns, keyed by the /v1/<collection> path segment
(def ^:private handlers
  {"wafers" {:create create-wafer :list list-wafers :get get-wafer :update update-wafer :delete delete-wafer}
   "processsteps" {:create create-process-step :list list-process-steps :get get-process-step :update update-process-step :delete delete-process-step}
   "reticles" {:create create-reticle :list list-reticles :get get-reticle :update update-reticle :delete delete-reticle}
   "processrecipes" {:create create-process-recipe :list list-process-recipes :get get-process-recipe :update update-process-recipe :delete delete-process-recipe}
   "defectscans" {:create create-defect-scan :list list-defect-scans :get get-defect-scan :update update-defect-scan :delete delete-defect-scan}
   "yields" {:create create-yield :list list-yields :get get-yield :update update-yield :delete delete-yield}})

(defn- expand-opts [params]
  (when-let [x (:expand params)]
    {:expand (set (map keyword (str/split (str x) #",")))}))

(defn dispatch
  "Route an HTTP-ish request through `routes` to the CRUD fns.
   req: {:method (:get/:post/:patch/:delete) :path /v1/<coll>[/<id>] :params {} :body {}}.
   Returns {:status int :body any} — the runnable L4 service surface."
  [port {:keys [method path params body]}]
  (let [segs (->> (str/split (or path "") #"/") (remove str/blank?) vec)
        coll (get segs 1)
        id   (get segs 2)
        h    (get handlers coll)
        params (or params {})]
    (cond
      (nil? h) {:status 404 :body {:error "unknown collection"}}
      (and (= method :post) (nil? id)) {:status 201 :body ((:create h) port (or body params))}
      (and (= method :get) (nil? id)) {:status 200 :body ((:list h) port params)}
      (and (= method :get) id) (if-let [r ((:get h) port id (expand-opts params))]
                                 {:status 200 :body r} {:status 404 :body {:error "not found"}})
      (and (#{:patch :put} method) id) (if-let [r ((:update h) port id (or body params))]
                                         {:status 200 :body r} {:status 404 :body {:error "not found"}})
      (and (= method :delete) id) {:status 200 :body ((:delete h) port id)}
      :else {:status 405 :body {:error "method not allowed"}})))

(defn healthz []
  {:status "ok" :actor "fab_lithography-compat" :tier "L4"
   :lang "clojure" :persistence "datomic-eavt-kotoba"
   :entities entities})
